import pygame

pygame.init()

background = pygame.image.load("assets/brick-wall.jpg")
brick_x = pygame.image.load("assets/brick_x.jpg")
brick_o = pygame.image.load("assets/brick_o.png")
ladder = pygame.image.load("assets/construction.png")
menu = pygame.image.load("assets/menu.png")
logo = pygame.image.load("assets/logo.png")
start = pygame.image.load("assets/arrows.png")
door = pygame.image.load("assets/door.png")
tower = pygame.image.load("assets/tower.png")
levels = pygame.transform.scale(pygame.image.load("assets/button_level.png"), (388, 146))
credit = pygame.transform.scale(pygame.image.load("assets/button_credit.png"), (388, 146))
won = pygame.image.load("assets/won.png")
level_choice = pygame.image.load("assets/level_choice.png")
one = pygame.image.load("assets/one.png")
two = pygame.image.load("assets/two.png")
three = pygame.image.load("assets/three.png")
intro = pygame.image.load("assets/intro.png")
trappe = pygame.image.load("assets/trappe.png")
key = pygame.image.load("assets/key.png")
closed_trap = pygame.image.load("assets/closed_trappe.png")
close = pygame.image.load("assets/close.png")
reset = pygame.image.load("assets/redo.png")